### ISSUE TITLE
"Trouble loading data"

### ISSUE THREAD

**Issue by MatthewRDodds** [kevintyll/ofac#10]
After installing (v3.0.0), generating and running migrations, I get this when trying to update the data:

```
pry(main)> OfacSdnIndividualLoader.load_current_sdn_file
Not using mysql, will use active record to load data
Reloading OFAC sdn data
Downloading OFAC data from http://www.treas.gov/offices/enforcement/ofac/sdn
Trouble downloading file.  The url may have changed.
```

Any ideas or suggestions are appreciated.

**Comment by MatthewRDodds** [comment]
I also tried reverting all of that and installing from v2.0.4 but encountered the same error.

**Comment by MatthewRDodds** [comment]
Okay, issue is that http redirects to https and the read fails to follow the redirect.

This was fixed in https://github.com/kevintyll/ofac/commit/15ca3b82e2d4b8a93c2c713c3709e84598158d7f

Can we get a version bump / new gem release?

**Comment by MatthewRDodds** [comment]
https://github.com/kevintyll/ofac/releases/tag/v3.0.1

Thanks!

**Comment by kevintyll** [comment]
I had merged the pull request, but apparently never pushed the gem.

**Comment by MatthewRDodds** [comment]
Much appreciated @kevintyll, thanks for this awesome gem as well
